### ISSUE TITLE
matchCondition requires methods property

### ISSUE THREAD

**Issue by davidmw** [shibayan/AppServiceProxy.SiteExtension#30]
Applying our proxies.json taken from a functional v3 Function App Proxy results in none of the routes working.

Taking your example proxies.json and deleting the methods property accomplishes a similar result:

`{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "proxy1": {
      "matchCondition": {
        "route": "/{*path}"
      },
      "backendUri": "https://shibayan.jp/{path}"
    }
  }
}`
returning a 503.

Using an empty array works:
`{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "proxy1": {
      "matchCondition": {
        "route": "/{*path}",
        "methods": []
      },
      "backendUri": "https://shibayan.jp/{path}"
    }
  }
}`

The intent in both cases is to support all methods.

**Comment by shibayan** [comment]
Fixed by #33
