### ISSUE TITLE
Support Function App or only Web App?

### ISSUE THREAD

**Issue by davidmw** [shibayan/AppServiceProxy.SiteExtension#32]
My first attempts to get this extension installed and working was on a Function App.  Creation of the function app (.NET V7.x, Windows) and configuration of the site extension can be achieved via the portal and bicep, seemingly without error but I've not been able to get the proxy to respond.

Running the Quick Start configured a Web App and the proxy starts working once the proxies.json file is uploaded.  

We had the legacy proxy running on a Windows Function App that was also serving a few API endpoints - so it was doing double duty.  This is not important, we can dedicate an app to the proxy function once we understand the constraints.

On our network upgrade we've been migrating all function apps from Windows to Linux. And we are staying with .NET 6.x LTS, intend to skip 7.x and migrate to 8 LTS when available.  

So on my wish list would be more flexibility - ideally we would not need an additional App Service Plan and the cost associated with it, just to host the proxy.

**Comment by shibayan** [comment]
Please try https://github.com/shibayan/azure-functions-http-api
